version: '3.3'
services:
  clcache_couchbase:
    build: .
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "8095:8095"
      - "8096:8096"
      - "8097:8097"
      - "11210:11210"
      - "11280:11280"
    environment:
      - COUCHBASE_ADMIN_PASSWORD=gdb*vrt.EYN3ufq6xwd
    volumes:
      - /mnt/data/couchbase:/opt/couchbase/var
