version: '3.3'
services:
  couchbase_sync:
    image: couchbase_sync:latest
    environment:
      - NODES=10.105.20.235,10.250.20.241
    deploy:
      replicas: 1
      restart_policy:
        delay: 60s
        window: 120s
