version: '3.3'
services:
  couchbase_sync:
    image: couchbase_sync:latest
    
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    
    networks:
      - couchbase_sync_net
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  couchbase_sync_net:
    driver: overlay

