version: '3.3'
services:
  couchbase_sync:
    image: couchbase_sync:latest
    environment:
      - NODES=10.105.20.201,10.250.20.241
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    networks:
      - couchbase_sync_net

networks:
  couchbase_sync_net:
    driver: overlay
