version: '3.3'
services:
  couchbase_clcache:
    image: us-docker.pkg.dev/inr-ci/inr-docker/couchbase_clcache:latest
    secrets:
      - couchbase_admin_password
    ports:
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
      - target: 8092
        published: 8092
        protocol: tcp
        mode: host
      - target: 8093
        published: 8093
        protocol: tcp
        mode: host
      - target: 8094
        published: 8094
        protocol: tcp
        mode: host
      - target: 11210
        published: 11210
        protocol: tcp
        mode: host
      
    volumes:
      - /mnt/data/couchbase:/opt/couchbase/var
    deploy:
      replicas: 2
      restart_policy:
        delay: 60s
        window: 120s

  couchbase_sync:
    image: us-docker.pkg.dev/inr-ci/inr-docker/couchbase_sync:latest
    environment:
      - NODES=10.105.20.235,10.250.20.241
    deploy:
      replicas: 1
      restart_policy:
        delay: 60s
        window: 120s

secrets:
  couchbase_admin_password:
    external: true
