name: Build and Release

on:
    release:
        types: [published]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t clcache -f docker/Dockerfile docker

      - name: Run Docker container to build and upload release
        env:
          CONAN_TOKEN: ${{ secrets.GLOBUS_CONAN_GOOGLE_CLOUD_ADMIN_TOKEN }}  # Conan token for authentication
        run: |
          docker run -v $PWD:/src clcache \
            bash -c "echo y | /opt/clcache/entrypoint.sh"
